pshriwise/xdg

- CMakeLists.txt
- include/xdg/geometry_data.h
- include/xdg/primitive_ref.h
- include/xdg/ray.h
- include/xdg/ray_tracing_interface.h
- include/xdg/triangle_ref.h
- include/xdg/xdg.h
- src/ray_tracing_interface.cpp
- src/triangle_intersect.cpp
- src/xdg.cpp
- tests/test_normal.cpp
The triangle reference (now primitive reference) doesn't need to hold the surface ID. That can be stored on the `GeometryUserData` object instead. This makes the reference that much smaller.
> TriangleRef --> PrimitiveRef and lean-out the representation

- src/moab/mesh_manager.cpp
- tools/particle_sim.cpp
The `MeshManager::element_bounding_box` method was exhibiting incorrect behavior because the starting bounding box was volume zero centered on the origin.
> Bounding box fix

- .gitmodules
- CMakeLists.txt
- include/xdg/vec3da.h
- tools/CMakeLists.txt
- tools/find_volume.cpp
- tools/particle_sim.cpp
- tools/point_in_volume.cpp
- tools/ray_fire.cpp
This updates the `particle-sim` tool to take a set of arguments to more easily hammer on changes in direction and ensure user understanding of the tool.
It also adds three new diagnostic tools:
- `ray-fire`
- `find-volume`
- `point-in_volume`
> More tools w/ arguments

- include/xdg/bbox.h
Initializes the values of `BoundingBox` to `0.0` for default construction.
> Fix bounding box junk values.

- include/xdg/mesh_manager_interface.h
- include/xdg/moab/mesh_manager.h
- include/xdg/util/str_utils.h
- src/mesh_manager_interface.cpp
- src/moab/mesh_manager.cpp
- src/util/str_utils.cpp
- tests/test_moab.cpp
- tests/test_overlap_check.cpp
I'd thought that the `xdg` branch in my fork of OpenMC was up to date, but it needed some adjustments. Namely it was missing the ability to ignore the "picked" group that often appears in DAGMC files and is meaningless, the ability to assign implicit complement materials (a frustrating catch 22 to deal with there), and assignment of boundary conditions for graveyard volumes.
These are all idiosyncrasies of the DAGMC file spec and points of origin, so I'm trying to keep additional code and logic manged in the `MOABMeshManager` as much as possible.
> Updates for OpenMC Compatability

- .github/workflows/openmc-test.yml
This adds a CI workflow for building the branch of OpenMC that uses XDG.
It will initially run the DAGMC tests in the OpenMC test suite to ensure the results are the same when using this library instead of DAGMC. Additional tests will be included based on the various backends of XDG and identically faceted models.
> Test with OpenMC

- include/xdg/vec3da.h
- src/overlap_check/overlap.cpp
There was an error in the `rand_dir` function for sampling the polar angle. This PR corrects that.
This caused the overlap checker tests to fail. It's unclear as to why b/c the point containment checks should be independent of the ray direction. I'm going to table that for now and create an issue to follow up on later.
> Fix random dir function. Use static direction in overlap checker for now

- .github/workflows/ci.yml
- .github/workflows/openmc-test.yml
This caches the MOAB build to speed up CI. I'll apply it to other dependencies as they come up.
> Cache build dependencies to speed up CI

- src/triangle_intersect.cpp
- tests/test_ray_fire.cpp
The primitive culling technique was using hit information about the primitive that was not yet set. The primitive ID is now directly passed to the culling function with these changes. 
A test has been added to ensure that primitive culling works correctly in `test_ray_fire`
> Fix primitive culling

- CMakeLists.txt
- cmake/XDGConfig.cmake.in
This implements a set of changes to support a wider set of Embree versions. Recently, CI broke here because the OS on GitHub actions updated and the new Embree debian package jumped to a version newer than 4.0. 
As a result of this I found out that the Embree CMake configuration (generated through CPack)  doesn't support version ranges at all. The cleanest way I could think of to remedy this is to call `find_package` twice, once with a minimum version 4.0.0 and then 3.0.0 if the first call isn't successful.
> Changes to CMake to support a wider range of Embree versions

- include/xdg/ray_tracing_interface.h
- include/xdg/xdg.h
- src/ray_tracing_interface.cpp
- src/xdg.cpp
- tests/test_ray_fire.cpp
- tools/particle_sim.cpp
Resolving issue #42 by adding the ability to specify an orientation to the `ray_fire` call by passing an explicit `HitOrientation` enum.
```
std::pair<double, MeshID> ray_fire(TreeID scene,
const Position& origin,
const Direction& direction,
const double dist_limit = INFTY,
std::vector<MeshID>* const exclude_primitives = nullptr,
HitOrientation orientation = HitOrientation::EXITING);
```
Default value is `EXITING` as most queries will be exiting I assume?
Added some asserts to the `test_ray_fire.cpp` file for using `ray_fire` with a ray orientation specifying whether or not the ray is querying for a `ENTERING` or `EXITING` intersection. Diagram of the rays being tested for below:
@pshriwise Am I missing anything else or is this working as expected?
> Expose ray orientation in ray_fire signature

- include/xdg/libmesh/mesh_manager.h
- include/xdg/mesh_manager_interface.h
- include/xdg/moab/mesh_manager.h
- src/embree/ray_tracer.cpp
- src/libmesh/mesh_manager.cpp
- src/mesh_manager_interface.cpp
- src/moab/mesh_manager.cpp
- src/overlap_check/overlap.cpp
- src/ray_tracing_interface.cpp
- src/triangle_intersect.cpp
- src/xdg.cpp
- tests/mesh_mock.h
- tests/particle_sim.h
- tests/test_bvh.cpp
- tests/test_libmesh.cpp
- tests/test_mesh_internal.cpp
- tests/test_moab.cpp
- tests/test_normal.cpp
This PR switches some of the method naming so that methods with `*_faces` refer to 2D elements and `*_elements` refers to volumetric, 3D elements.
This is primarily to disambiguate the methods that collect all of the volume triangles from methods that I'll introduce to collect all of the volumetric elements when particles are walking element-to-element.
> Method nomenclature

- docs/methods/design_philosophy.rst
This PR adds an embedded link to a UML diagram I am working on for XDG. Right now there is no extra styling and is literally just the html produced by draw.io to link to the draw.io diagram saved in my google drive, embedded directly in the documentation. 
The current plan is for this diagram to live in the design philosophy section of the documentation but I am happy for it to move if it makes sense to go somewhere else.
> Adding a UML diagram to the documentation

- include/xdg/error.h
- src/error.cpp
Super minor PR that adds the [[noreturn]] attribute to the `fatal_error()` function defined in `error.h`. 
Since `fatal_error()` always results in exiting the application the control logic will never return to the caller - `[[noreturn]]` explicitly specifies this to the compiler, which should suppress the compiler warning: `warning: no return statement in function returning non-void [-Wreturn-type]`.
> Added [[Noreturn]] attribute on XDG fatal errors

- CMakeLists.txt
- include/xdg/constants.h
- src/xdg.cpp
Refactored the `xdg::create()` method to make use of a set of lambda functions for extra encapsulation in setting the back-end libraries XDG is instantiated with. Should hopefully allow for a cleaner more extensible structure as more back-end libraries are added.
> Refactor xdg create

- docs/methods/element_search.rst
- docs/methods/index.rst
- docs/methods/primitive_intersection.rst
- include/xdg/geometry_data.h
- include/xdg/ray.h
- include/xdg/tetrahedron_contain.h
- src/embree/ray_tracer.cpp
- src/tetrahedron_contain.cpp
- src/triangle_intersect.cpp
This adds the set of callbacks needed for Embree to use the tetrahedron containment check function.
A new struct, `RTCElementRay` that supports discovery of a containing element with a zero-length array. Some high-level notes have been added to describe the process by which element searches will occur using these methods.
In isolation, these callbacks don't add any functionality to the library, but I feel it's a relatively coherent starting point before adding the code that includes the construction of and querying of Embree geometries and scenes.
> Embree tetrahedral search callbacks

- include/xdg/ray.h
- tests/CMakeLists.txt
- tests/test_ray_duals.cpp
This adds some basic unit tests for the various extended `struct` types defined in `ray.h`.
> Adding tests for extended Embree structs

- .github/workflows/ci.yml
- include/xdg/libmesh/mesh_manager.h
- include/xdg/mesh_manager_interface.h
- src/libmesh/mesh_manager.cpp
I noticed when building against a debug version of libMesh that we are triggering some assertions in testing due to the way the `LibMeshManager` deconstructor is formed.
An example of this happening in CI is here from the first commit in this branch:
https://github.com/pshriwise/xdg/actions/runs/15625258511/job/44018149010
This PR corrects the issues with the constructor and attribute ordering in the `LibMeshManger` class. It also sets the `METHOD` environment variable to `dbg` in CI, which will ensure that such assertions are triggered in CI in the future. I'm okay with linking against a debug build here b/c we're more concerned with correctness/consistency in CI than performance.
> libMesh initialization fix

- include/xdg/embree/ray_tracer.h
- include/xdg/geometry_data.h
- include/xdg/primitive_ref.h
- include/xdg/ray.h
- src/embree/ray_tracer.cpp
- src/ray_tracing_interface.cpp
- src/triangle_intersect.cpp
Wanted to get a draft PR up to resolve #4. 
- Added a `MeshID` for forwards and reverse sense to the `GeometryUserData` struct
- Replaced previous references to `primtive_ref.sense` to use the new members in the `GeometryUserData`
**Question** - in #4 its mentioned that an idea of the scene a ray is being fired upon would need to be stored in `RTCDRay`. I notice that `RTCDRayHit` already defines a `geomID`: 
```
struct RTCDHit : RTCHit {
RTCDHit() {
this->geomID = RTC_INVALID_GEOMETRY_ID;
this->primID = RTC_INVALID_GEOMETRY_ID;
this->Ng_x = 0.0;
this->Ng_y = 0.0;
this->Ng_z = 0.0;
}
```
Is this `geomID` not that scene the ray is being fired upon? Should `RTCDRay` also additionally store a `geomID` or `sceneID`?
> Resolve #4 to remove the extra triangle references being stored

- include/xdg/moab/direct_access.h
- src/moab/direct_access.cpp
This refactors the direct access objects used to query MOAB face and element data so that elements and faces use the same data structure to reference vertex coordinates. IMO it makes the process of vertex coordinate lookups for these types easier to follow.
> MOAB direct access refactor

- include/xdg/constants.h
- include/xdg/embree/ray_tracer.h
- include/xdg/error.h
- include/xdg/geometry_data.h
- include/xdg/libmesh/mesh_manager.h
- include/xdg/mesh_manager_interface.h
- include/xdg/moab/mesh_manager.h
- include/xdg/ray_tracing_interface.h
- include/xdg/xdg.h
- src/embree/ray_tracer.cpp
- src/mesh_manager_interface.cpp
- src/moab/mesh_manager.cpp
- src/ray_tracing_interface.cpp
- src/triangle_intersect.cpp
- src/xdg.cpp
- tests/CMakeLists.txt
- tests/mesh_mock.h
- tests/test_bvh.cpp
- tests/test_find_element.cpp
- tests/test_libmesh.cpp
- tests/test_mesh_internal.cpp
- tests/test_moab.cpp
- tests/test_occluded.cpp
- tests/test_point_in_volume.cpp
- tests/test_ray_fire.cpp
This PR uses the Embree-based element trees from #121 to implement element searches given locations in the mesh for both MOAB and libMesh.
Noting here that at some point it may useful to provide "native" or "pass-through" options to use the mesh library native data structures (#30).
Marking this as draft right now because the mechanics have been pulled in from #102 but I'd like to look it over and clean up the code (and possibly design) first.
> Enabling find_element operations

- include/xdg/moab/mesh_manager.h
- src/moab/mesh_manager.cpp
This PR replaces direct calls to MOAB's `tag_get_data` methods. The primary motivation for this was the discovery in #143 that passing an empty to container to these methods results in a segfault within MOAB. Adding wrappers to perform a defensive check in a few places makes more sense than including them at a higher level, and at that point templating the methods also makes sense so we don't have a wrappers for each datatype we're gathering. There are a couple of methods that also enable us to get a single value for a single-handle query, which admittedly aren't necessary but it's quite convenient to be able to do:
```cpp
int dim = this->tag_data<int>(geometry_dimension_tag_, entity);
```
instead of 
```cpp 
int dim;
this->moab_interface()->tag_get_data(geometry_dimension_tag_, &entity, …
```
> Simplify MOAB tag data retrieval
